name: eunice_repository
description: Repository for Eunice project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  eunice_entity:
    path: ../entity

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.5
  very_good_analysis: 5.1.0
