name: eunice_usecase
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  eunice_entity:
    path: ../entity
  eunice_repository:
    path: ../repository

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.5
  very_good_analysis: 5.1.0
